//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace create_lib_reference {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("create_lib_reference.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 copy_src = $$shell_path($$absolute_path($$PWD/{0}))
        ///copy_des = $$shell_path($$absolute_path($$DESTDIR))
        ///
        ///package_bin_{1}.src.dirs = $$copy_src
        ///package_bin_{1}.des = $$copy_des
        ///COPIES += package_bin_{1}
        ///
        ///unset(copy_src)
        ///unset(copy_des)
        /// 的本地化字符串。
        /// </summary>
        internal static string copy_reference_dir {
            get {
                return ResourceManager.GetString("copy_reference_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exists($$PWD/{0}-default.pri) {{
        ///    include($$PWD/{0}-default.pri)
        ///}}
        ///
        ///if(!debug_and_release|build_pass):CONFIG(debug, debug|release) {{
        ///    include($$PWD/{0}-debug.pri)
        ///}} else {{
        ///    include($$PWD/{0}-release.pri)
        ///}} 的本地化字符串。
        /// </summary>
        internal static string default_base {
            get {
                return ResourceManager.GetString("default_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LIBS *= -L$$PWD/{0}/ -l{1}
        ///INCLUDEPATH *= $$PWD/{2}
        ///DEPENDPATH *= $$PWD/{2} 的本地化字符串。
        /// </summary>
        internal static string default_import {
            get {
                return ResourceManager.GetString("default_import", resourceCulture);
            }
        }
    }
}
