name: Build

on:
  pull_request:
    branches: 'master'
    paths:
      - "**"
      - "!**.MD"
      - "!LICENSE"
      - "!.gitignore"
  push:
    branches: 'master'
    tags: 'v*'
    paths:
      - "**"
      - "!**.MD"
      - "!LICENSE"
      - "!.gitignore"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: "src" 
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
      
    - name: Build with dotnet
      run: dotnet build --configuration Release src
    
    - name: Create artifact
      if: always() && !startsWith(github.event_name, 'pull_request')
      uses: actions/upload-artifact@v1.0.0
      with:
        name: create-lib-reference
        path: src/create-lib-reference/bin/Release/create-lib-reference.exe
    
    - name: Upload release
      if: always() && startsWith(github.ref, 'refs/tags/v')
      uses: yakuhzi/action-release@v1
      with:
        file: src/create-lib-reference/bin/Release/create-lib-reference.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: Checkout pri
      if: always() && !startsWith(github.event_name, 'pull_request')
      uses: actions/checkout@v2
      with:
        path: "pri"
        repository: sanjusss/qt-deploy-pri
    
    - name: Modify pri
      if: always() && !startsWith(github.event_name, 'pull_request')
      run: cp -f ./src/create-lib-reference/bin/Release/create-lib-reference.exe ./pri/tools/
      shell: bash
    
    - name: Commit files
      if: always() && !startsWith(github.event_name, 'pull_request')
      run: |
        cd ./src/
        git config --local user.email "sanjusss@qq.com"
        git config --local user.name "sanjusss"
        git commit -m "Update tools by bot." -a
      shell: bash
        
    - name: Push pri
      if: always() && !startsWith(github.event_name, 'pull_request')
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: sanjusss/qt-deploy-pri
        directory: ./src/
